language: python
node_js:
- '3.6'
env:
  global:
  - AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY_ID
  - AWS_DEFAULT_REGION=us-east-2
branches:
  only:
  - master
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script: make build