language: python
python:
- '3.6'
env:
  global:
  - AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY_ID
  - AWS_DEFAULT_REGION=us-east-2
branches:
  only:
  - master
before_install:
- pip install --upgrade awscli
- export PATH=$PATH:$HOME/.local/bin
script: ./upload.sh